print("first python file in github,in my cuurent repo")
print("making an calculator using arthimetic operarions")
a=int(input("enter the first element :"))
b=int(input("enter the second element:"))
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Modules:",a%b)
print("outputs are given above")